# Generated by Django 5.2.6 on 2025-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('musician', 'Musician'), ('band', 'Band Admin'), ('admin', 'Administrator')], default='musician', max_length=50),
        ),
    ]
